<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>2024-09 on ZZZ's Blogs</title><link>https://zl6977.github.io/tags/2024-09/</link><description>Recent content in 2024-09 on ZZZ's Blogs</description><generator>Hugo</generator><language>en-us</language><lastBuildDate>Tue, 03 Sep 2024 15:48:58 +0200</lastBuildDate><atom:link href="https://zl6977.github.io/tags/2024-09/index.xml" rel="self" type="application/rss+xml"/><item><title>Python requests lib throws SSL error in company network</title><link>https://zl6977.github.io/obsidian/python-requests-lib-throws-ssl-error-in-company-network/</link><pubDate>Tue, 03 Sep 2024 14:30:16 +0200</pubDate><guid>https://zl6977.github.io/obsidian/python-requests-lib-throws-ssl-error-in-company-network/</guid><description>&lt;h1 id="python-requests-lib-throws-ssl-error-in-company-network">Python requests lib throws SSL error in company network&lt;/h1>
&lt;h2 id="short-version简短版">Short version/简短版&lt;/h2>
&lt;p>Python requests lib is not using the certificate in system certificate manager, which means it can not find a usable certificate like your browser.
So, the solution is to add the root certificate to the PEM file that python is using. Normally the root certificate is issued by your company, which can be checked in your browser.
Then a working verification chain for python requests lib can be established.
See a solution directly: [[#Solution 2 Alternative fix using a lib]]. I did not not try with this. If it does not work, use [[#Solution 1 Manual fix]].
This problem does not happen on my personal computer, because there is no proxy generating a self-signed certificate.&lt;/p></description></item></channel></rss>